# Generated by Django 4.0.5 on 2022-08-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recycled',
            field=models.BooleanField(default=False),
        ),
    ]
